### ISSUE TITLE
Wine always starts debugger on exit

### ISSUE THREAD

**Issue by wvreeven** [Gcenx/homebrew-wine#1]
Thanks for making this available! I am finally able to run windows apps on Catalina again.

Whenever wine64 exists, it gives this error and attempts to start the debugger:

wine: Unhandled page fault on read access to 0xffffffffffffffff at address 0x7fff342dfba7 (thread 001a), starting debugger...

Do you know if this is something in your Cask or something in the Crossover code? Any plans to upgrade to newer Crossover code?

Thanks, Wouter

**Comment by Gcenx** [comment]
That’s one of the things CodeWeavers never gotten around to resolving before release.

This was built from CrossOver-19.0.1 source plus a couple of simple patches you can see the exact source here https://github.com/Gcenx/winecx

When I have time I’ll lightly rebuild this again with some additional patches I’ve been working on and set the debugged to disabled by default.

**Comment by wvreeven** [comment]
Thanks for the explanation and sorry for not reading the full docs that you provided. Apart from that everything is working beautifully well so thanks again for making this available!
