### ISSUE TITLE
Do you plan to build wine-crossover 20.* ?

### ISSUE THREAD

**Issue by bikeridercz** [Gcenx/homebrew-wine#10]
Dear friend, let me just ask ... do you plan to build a wine-crossover based on latest crossover-wine-20.0.2 ? Thanks for your great work !

**Comment by Gcenx** [comment]
This has been asked before #8 and also within https://github.com/Gcenx/WineskinServer/issues/65#issuecomment-753679873, until I hear back from Jeremy with a resolution for Ticket 1285116 I won't be upgrading wine-crossover.

**Comment by alexchandel** [comment]
Could you link that ticket?  And could you please reconsider?  Wine 5.0.x has tons of bugfixes & new features for Intel macs.

**Comment by Gcenx** [comment]
@alexchandel I'm unable to link to tickets on CodeWeavers site, Tickets are only relevant to the person who opened them and there internal Ticking system is not directly mapped to the client ticket(s).\
As I'm also part of there "BetterTester" program even _if_ it were possible it wouldn't be a good idea.

I won't be updating `wine-crossover` until I have WineCX20 running decently under Rosetta2, this isn't a huge improvement over WineCX19 it actually contains tons of regressions that Wine-5.0.x doesn't have.\
I'll also need to confirm WineCX20.0.x really function below macOS High Sierra as the new GPU detection code uses a feature only added in macOS High Sierra (it fails to display under my test VMs)

The only real improvements within CrossOver-20.0.x were;
- Microphone working within wine32on64
- Better permission handling (improved in 20.0.2)
- Midi support (20.0.1)

DXVK support will be out of scope for the cask so the modified MoltenVK nor the DXVK dlls will be shipped within the cask.

**Comment by Gcenx** [comment]
If acceptable I could add another cask that would provide a very minimal build of WineCX20, allow me to leave the current more stable version in place.

**Comment by Gcenx** [comment]
Closing with https://github.com/Gcenx/homebrew-wine/commit/86e38240984a0883c4b66fd774b20b48c392e2d4 I’ll consider this resolved.\
The package is as barebones as it gets but I’m sure it will be of some use until I replace it with a _real_ package later.
