### ISSUE TITLE
Error: OSMesa not compiled in, no OpenGL bitmap support

### ISSUE THREAD

**Issue by mauricelos** [Gcenx/homebrew-wine#11]
Hi,

I stubbled up on this error. I'm not sure if this is caused by homebrew-wine or if it's something general with the program I want to run. Here is the full message from wine console:

```
0135:fixme:wgl:macdrv_wglCreatePbufferARB WGL_PBUFFER_LARGEST_ARB: 1; ignoring
0135:err:dib:dibdrv_wine_get_wgl_driver OSMesa not compiled in, no OpenGL bitmap support
Unable to set pixel format 0
Unable to set pixel format 0
 A system exception occurred 0xc0000005
```

I'm using the wine-crossover as per the instruction in the README.md. I'm running macOS Big Sur 11.1 on a i7 4790k without graphics card (if this is even relevant)

**Comment by Gcenx** [comment]
As your running macOS Big Sur the binary being used is wine32on64 doesn’t support all features (build errors) so they need to be disabled, one of them being `--without-x11` It’s possible when that’s passed to configure osmesa also gets disabled.

When you say no graphics card you mean no dedicated GPU?, not sure if that’s relevant.

**Comment by mauricelos** [comment]
Oh I see, do you think this can be resolved in newer versions?

Yes, I mean no dedicated graphics, my computer is running on the integrated graphics of the intel chip.

**Comment by Gcenx** [comment]
I’d think CodeWeavers could resolve this but I don’t think it’s very lightly, can you tell me what you were attempting to run that caused this?, it might help when opening a ticket with CodeWeavers

**Comment by mauricelos** [comment]
Sure, I was trying to run Catia V5 R21. Strangely it happened when I tried to save a file. Besides that it works fine. 

I will try to run it in Linux when I have time to rule out any other issues with the program perhaps.

**Comment by mauricelos** [comment]
Just an addition to above comment: 

I tested on Ubuntu 18.04 with wine 6.0 and Catia V5 R21 works as expected. Saving a file doesn't not crash the program here.

**Comment by Gcenx** [comment]
Wine on Linux should be built with osmesa or it would be rather broken. This can be added to one of the 32on64 annoyances.

But just to be sure I’ll verify if osmesa is part of XQuartz (I’m sure it is)

**Comment by Gcenx** [comment]
This doesn’t seem to be something I can resolve and I’m not sure if CodeWeavers will ever bother getting this working in 32on64 outside of it being added to upstream and needing to work on Linux.
