### ISSUE TITLE
msado15:connection_QueryInterface interface not implemented

### ISSUE THREAD

**Issue by bikeridercz** [Gcenx/homebrew-wine#12]
Dear Friend,

it is definitely NOT a problem of a build, so it is just a question where to report this issue ... ?

My application (EA.exe) requires a connection to remote database via ODBC MySQL driver. During a connection an error appears on the terminal screen ...
```
003e:fixme:msado15:connection_QueryInterface interface {00000126-0000-0000-c000-000000000046} not implemented
003e:fixme:msado15:connection_Open 20B80D80, L"Provider=MSDASQL.1;Persist Security Info=False;Data Source=Maria;", L"", 20B0E53C, 00000000
003e:fixme:msado15:supporterror_InterfaceSupportsErrorInfo 20B80D80, {00000515-0000-0010-8000-00aa006d2ea4}
003e:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 06C3FD1C
```

There is a simple WA to this issue, msdao15 shall be set to NATIVE using winecfg. It was already fixed in Wine5 (https://bugs.winehq.org/show_bug.cgi?id=48336).

Thanks for an advice where to report this issue.

BTW this build of Wine Crossover (20.0.2) works definitely faster than the previous version 19.0.2 :-)

**Comment by Gcenx** [comment]
Usually you can report unimplemented features directly to CodeWeavers and it’s always good to also link to a Winehq bug report.

But in this case I wouldn’t considering the bug was fixed in wine-5.20 according to the closing comment, meaning that CX21 should include this bug fix by default as CX21 will be based on Wine-6.0.

**Comment by bikeridercz** [comment]
So, shall I open the Bug#48336 again and report regression in Wine-6.0 ? Thanks.

**Comment by Gcenx** [comment]
Wait for CX21 and did it this still happens for some reason you open a support ticket on CodeWeavers site and explain the issue and provide them with the Winehq bug.

You don’t post CX bugs in Winehq as it’s a third-party project not the main Winehq project.

**Comment by Gcenx** [comment]
Closing as this issue will be resolved within CX21 when available.
