### ISSUE TITLE
small difference in 19.0.2 and 20.0.2 wine executable

### ISSUE THREAD

**Issue by bikeridercz** [Gcenx/homebrew-wine#13]
Dear Friend, I'm reporting a small difference between release 19 and 20. While running 32bit application there is a need to call **wine32on64** explicitly in release 20. On the other hand in release 19 it was enough to call just **wine** executable, what seem to be little easier for regular users. No action is required I think. Thanks.

**Comment by Gcenx** [comment]
Yes that’s correct I removed the wrapper script that was included in CX19, this was to avoid permissions problems for anyone incorrectly calling /usr/local/bin/wine, it’s more correct to directly call `wine32on64` or instead call `wine64` as this will call the correct binary depending on macOS version.
