### ISSUE TITLE
How was the Release compiled

### ISSUE THREAD

**Issue by Endle** [Gcenx/homebrew-wine#14]
Hi, while discussing at https://github.com/madewokherd/wine-mono/issues/84 I have some questions about this repo
The artifacts are uploaded at https://github.com/Gcenx/macOS_Wine_builds/releases , where can I find the scripts to compile wine source code and publish them?

As we may compile wine-git for wine-mono, I'd like to reuse the compile scripts & configures at here. It could both save our human efforts and provide similar environments for development & users

**Comment by Gcenx** [comment]
Unfortunately macos_winebuild doesn’t handle the uploading of assets to GitHub at this time and can’t function within GitHub actions.

To duplicate my setup you’d require an Intel mac running macOS Mojave (or an Intel hackintosh running macOS Mojave), you’d also need to use [macports-wine](https://github.com/Gcenx/macports-wine) to deal with annoyances.

I’d started to work on compiling wine64 for macOS using GitHub actions last night, building works and uploading artifacts to actions works, but I received an email saying I’ve hit the free limit of 2000 mins (33 hours) for the month so that’s something to also take into consideration.

Feel free to contact me privately.

**Comment by Endle** [comment]
Hi,
I suppose there should be a script file for compile configuration, like
```
patch xxx.diff
CFLAGS=xx ./configure --enable-xxx --disable-xxx
make 
cp -r ./build $(dist)
```

I've been finding such file in macOS_Wine_build and

**Comment by Gcenx** [comment]
Here's basically the configuration I'm using;

Environment 
```
# Make dlopen() function like wine_dlopen()
export LDFLAGS="-Wl,-headerpad_max_install_names,-rpath,@loader_path/../,-rpath,/opt/local/lib,-rpath,/opt/X11/lib"

# Set headers
export C_INCLUDE_PATH="/opt/local/include"
export CPLUS_INCLUDE_PATH="$C_INCLUDE_PATH"
export OBJC_INCLUDE_PATH="$C_INCLUDE_PATH"

# Set library's
export LIBRARY_PATH="/opt/local/lib"

# Set Frameworks
export FRAMEWORK_SEARCH_PATHS="/opt/local/Library/Frameworks"
```

</br>

wine;
```
configure                   --prefix="" \
                            --without-alsa \
                            --without-capi \
                            --with-cms \
                            --with-coreaudio \
                            --with-cups \
                            --without-dbus \
                            --with-faudio \
                            --without-fontconfig \
                            --with-freetype \
                            --with-gettext \
                            --without-gettextpo \
                            --without-gphoto \
                            --with-gnutls \
                            --without-gsm \
                            --without-gssapi \
                            --with-gstreamer \
                            --without-hal \
                            --without-inotify \
                            --with-jpeg \
                            --with-jxrlib \
                            --without-krb5 \
                            --with-ldap \
                            --with-mingw \
                            --with-mpg123 \
                            --without-netapi \
                            --with-openal \
                            --with-opencl \
                            --with-opengl \
                            --with-osmesa \
                            --without-oss \
                            --with-pcap \
                            --with-png \
                            --with-pthread \
                            --without-pulse \
                            --without-quicktime \
                            --without-sane \
                            --with-sdl \
                            --with-tiff \
                            --without-udev \
                            --with-unwind \
                            --with-usb \
                            --without-v4l2 \
                            --without-vulkan \
                            --without-vkd3d \
                            --with-xcomposite \
                            --with-xcursor \
                            --with-xfixes \
                            --with-xinerama \
                            --with-xinput \
                            --with-xinput2 \
                            --with-xml \
                            --with-xrandr \
                            --with-xrender \
                            --with-xshape \
                            --without-xshm \
                            --with-xslt \
                            --with-xxf86vm \
                            --with-x \
                            --x-include=/opt/X11/include \
                            --x-lib=/opt/X11/lib
```

</br>

wine64;
```
configure                   --enable-win64 \
                            --with-vkd3d \
                            --with-vulkan \
                            ac_cv_lib_soname_MoltenVK=libMoltenVK.dylib \
                            ac_cv_lib_soname_vulkan=
```

</br>

Make configuration;
```
make -j$(sysctl -n hw.ncpu 2>/dev/null)
make install DESTDIR="$PREFIXFOLDER"
```
</br>
</br>

However those won't be viable for your needs without adding a custom GitHub runner, instead these will do the job
```
brew install bison mingw-w64
# bison is cellar only 
export PATH="$(brew --prefix bison)/bin:$PATH"

# download wine sources however you like
cd $SOURCES

# Not sure if its still needed to avoid linker issues;
export MACOSX_DEPLOYMENT_TARGET=10.14

./configure --enable-win64
make -j$(sysctl -n hw.ncpu 2>/dev/null)
make install
```

No need to set prefix unless you don't want to install into `/usr/local`

**Comment by Endle** [comment]
Thank you! These configuration is very helpful. 

>  but I received an email saying I’ve hit the free limit of 2000 mins (33 hours) for the month so that’s something to also take into consideration.

It's interesting that there is such a limit. I can't find anything related to it on Github Action public policy: https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration#artifact-and-log-retention-policy

**Comment by Gcenx** [comment]
Your welcome, the provided configuration should give you the latest issues.

Ive attached the warning emails I’ve received from GitHub.

<br>

![FC8BE9BB-99DF-43DD-BD03-5C9BD5400102](https://user-images.githubusercontent.com/38226388/109502727-5c148180-7a67-11eb-9a95-c5cd1e4c9606.png)

<br>

Also received one for the shared storage
![64363F46-95D9-440B-B093-C4F815EFAD2B](https://user-images.githubusercontent.com/38226388/109502909-99790f00-7a67-11eb-8f37-b76d3dd4d7a3.png)
512MB limit.

**Comment by Endle** [comment]
Thanks. Seems that this limit applies to private repos. Maybe public repos also have such a limit but I have not hit it yet.

I'm trying to gather all of these scripts to a public repo: https://github.com/Endle/mac_wine_compile
My proposal is, at every place we're going to compile wine on macOS, including wine-mono, we point to the same scripts. If wine build failed, we could fix it at the proper place.

If you're interested in it I can add you as a collaborator or transfer this repo to you

**Comment by Gcenx** [comment]
It’s possible it’s just a private repository limit but GitHub doesn’t list all these limits sigh..., ironically the private repository was for building wine64 for macOS using GitHub actions.

I don’t mind helping but I’d like to have an idea what the intentions are for the repository?

If the reason for building wine64 is for testing wine-mono then this can be gotten up an running quickly.

If the intention is to attempt to mirror what I’ve been doing that would be much harder to do using homebrew and GitHub actions and would require a custom GitHub runner.

**Comment by Endle** [comment]
> I don’t mind helping but I’d like to have an idea what the intentions are for the repository?
> 
> If the reason for building wine64 is for testing wine-mono then this can be gotten up an running quickly.
> 
My initial purpose is building wine64 for wine-mono. However, I prefer to put the build script to a place separately, instead of putting them under wine-mono.
@madewokherd what do you think of it?

> If the intention is to attempt to mirror what I’ve been doing that would be much harder to do using homebrew and GitHub actions and would require a custom GitHub runner.

If there is no plan to move all your work to github action, I don't think it worth the effort to mirror what you have done. My further goal is that if we could maintain such a repo, it may be a reference for those who want to compile wine on their macOS. We could add a link from https://wiki.winehq.org/MacOS/Building to the new git repo

**Comment by madewokherd** [comment]
A good place for it would probably be https://github.com/fgouget/wt-daily/blob/master/wt-install-dev

But, I don't think it's really worth it if no one will use it outside of wine-mono. I think I underestimated the amount of work involved when I brought up the idea. I'll use it if you want to do the work, but I think it's fine to use Gcenx's packages.

Incidentally, I am likely to run into that time limit for actions.

**Comment by Endle** [comment]
> But, I don't think it's really worth it if no one will use it outside of wine-mono. I think I underestimated the amount of work involved when I brought up the idea. I'll use it if you want to do the work, but I think it's fine to use Gcenx's packages.

IMHO we could add the link to this Github action to wiki page https://wiki.winehq.org/MacOS/Building
It may be a more detailed guide

**Comment by Gcenx** [comment]
> My initial purpose is building wine64 for wine-mono. However, I prefer to put the build script to a place separately, instead of putting them under wine-mono.

Yeah but for wine-mono the additional amount of time doesn't make sense I keep my casks functional so if say wine-6.4 breaks I don't provide that until an upstream patch fixes then. Currently wine-staging-6.3 is broken for macOS for example.

> If there is no plan to move all your work to github action, I don't think it worth the effort to mirror what you have done. My further goal is that if we could maintain such a repo, it may be a reference for those who want to compile wine on their macOS. We could add a link from https://wiki.winehq.org/MacOS/Building to the new git repo
> IMHO we could add the link to this Github action to wiki page https://wiki.winehq.org/MacOS/Building

The problem is that's then a third-party utility, that being the reason I haven't added macports-wine/macOS_Wine_builds/homebrew-wine etc.


> A good place for it would probably be https://github.com/fgouget/wt-daily/blob/master/wt-install-dev

That would need to check additional checks to deal with macOS and figure out what package manager is being used.

> But, I don't think it's really worth it if no one will use it outside of wine-mono. I think I underestimated the amount of work involved when I brought up the idea. I'll use it if you want to do the work, but I think it's fine to use Gcenx's packages.

That would save 43 min (build is 34 mins), it's not worth providing wine64 build using brew as once they change the formula in homebrew-core the package could become useless.

> Incidentally, I am likely to run into that time limit for actions.

Not sure if there's a public repository limit but better to safe than sorry.

**Comment by Gcenx** [comment]
@Endle it took a little tweaking (still needs some cleanup) but I’ve managed to build wine-git & wine-staging (wine64 only) using homebrew and Macports within GitHub actions.

**Comment by Gcenx** [comment]
I’m going to commit a `wine` formula if anything that could be used with the --head command to compile wine64 from head.
