### ISSUE TITLE
20.0.2 "terminals database is inaccessible"

### ISSUE THREAD

**Issue by Kethen** [Gcenx/homebrew-wine#16]
with bigsur 11.0.1 and 11.2.3
installed 20.0.2 today through brew, attempting to launch winecfg (while creating a new prefix) gets
```
terminals database is inaccessible
```
wine-crossover@19.0.2 seems to have the same issue..?

update: downloading the 19.0.2 tarball manually fixes the issue, and I suspect the real issue with brew cask is 
```
err:thread:get_image_addr dyld image info is above 4GB limit for 32-bit-on-64-bit process
```

**Comment by Gcenx** [comment]
Ah yea I’d forgotten about this change, upstream wine no longer directly uses ncurses where older version do.

I’ll modify the packages later.

When you manually download and unpatched you used the older package not the newer tar.xz package.

For wine-crossover@19.0.2 are you by chance using an M1 Mac?

**Comment by Kethen** [comment]
nope, I'm not on a M1 mac

also tried the 20.0.2 tarball and that works too

**Comment by Gcenx** [comment]
The older none xz package(s) are using a much older runtime and missing some needed patches, the issue is just the bundled ncurses dylibs need to be replaced.

The wine-crossover@19.0.2 one is a little irritating guess I need to backport even more changes from CX20 sources.

**Comment by Gcenx** [comment]
@Kethen `wine-crossover` should no longer have this issue now.

**Comment by BaconWrappedShrimpWithEyes** [comment]
I was having this issue when I updated yesterday. I was looking for a way to rollback and was going to open an issue, but it seems that it's working properly again.

**Comment by Kethen** [comment]
can confirm it works now too, closing the issue since 19.0.2 is tracked by #15
