### ISSUE TITLE
Wine-Crossover 20.0.2 bundle doesn't allow double-click launch on 64-bit-only macOS

### ISSUE THREAD

**Issue by Croosade** [Gcenx/homebrew-wine#17]
I've investigated the app bundle and, upon reversing the `MacOS/wine` binary, found that the `open_with_wine` function has a hard-coded path `wine/bin/wine`. On Catalina and Big Sur, this immediately exits because it's for the wrong architecture. It needs an OS version check similar to the one in the Bash wrapper script that was made for winetricks.

Are there sources for this Mac-specific `wine` launcher binary anywhere? I couldn't find anything about how it's built.

**Comment by Gcenx** [comment]
I’m considering to just use `wine64` instead.

The `open_with_wine` function always uses the default wineprefix that should be wow64 so using `wine64` instead makes more sense to me.

**Comment by Croosade** [comment]
I've located the wrapper souce [here](https://github.com/wine-compholio/wine-packaging/blob/master/packaging-wine/macosx/osx-package/wrapper.m) and tried the `wine64` change. It worked fine, so that does indeed seem like a viable solution.

**Comment by Gcenx** [comment]
Yes I’d forked that repository sometime ago.

While that does indeed work maybe it’s not the best way to deal with this, there’s alternatives that still need to be explored.

The shell script for winetricks compatibility need to be replaced with a cleaner method.

But until the current “can we get Origin working” is resolved this won’t be updated unfortunately.

**Comment by Gcenx** [comment]
@Croosade when you get chance could you try one of the recently pushed wine packages, each _should_ allow using wine64 when on macOS Catalina and greater.

If that works for you I’ll use the same technique for wine-crossover when I rebuilt that.

**Comment by giovariot** [comment]
Wouldn't it be a nicer solution to simply:

- rename `wine/bin/wine` in `wine/bin/wine32`
- edit `start/bin/wine` to run `wine/bin/wine32` on pre macOS Catalina versions
- link `start/bin/wine` to `wine/bin/wine`

That way the compatibility with earlier versions would be kept.
I'm on big sur and simply applying these steps solved the problem for me.

(thanks a lot for the great work btw)

**Comment by Gcenx** [comment]
@giovariot having the app bundle launching a wrapper script will end-up causing permission annoyances. Wineskin only uses wrapper scripts for `winetricks`

I have gotten a working solution for the app bundle launcher in the upstream wine packages, this launches `wine` or `wine64` depending on macOS version this will be modified for `wine-crossover` in the next rebuild.

The `wine` wrapper is for `winetricks`, renaming the binaries will cause problems for prefix creation. Looking into an alternative solution so the wrapper script can be removed entirely.

**Comment by giovariot** [comment]
Is there any chance this could be fixed too? :) thanks a lot for the great work
