### ISSUE TITLE
0009:err:mscoree:CLRRuntimeInfo_GetRuntimeHost Wine Mono is not installed

### ISSUE THREAD

**Issue by AnupPlays** [Gcenx/homebrew-wine#18]
When trying to run an .exe on MacOS Big Sur, this error is popping up. Full logs below:

err🧵get_image_addr dyld image info is above 4GB limit for 32-bit-on-64-bit process
000b:fixme🧵create_user_shared_data_thread Creating user shared data update thread.
000d:fixme🧵create_user_shared_data_thread Creating user shared data update thread.
0010:fixme🧵create_user_shared_data_thread Creating user shared data update thread.
0017:fixme🧵create_user_shared_data_thread Creating user shared data update thread.
001d:err:plugplay:process_IOService_Device object 0x6303
0019:err:plugplay:load_function_driver AddDevice failed for driver L"winebus", status 0xc0000002.
001d:err:plugplay:process_IOService_Device Unable to create plug in interface for USB deviceobject 0x6307
001d:err:plugplay:process_IOService_Device Unable to create plug in interface for USB deviceobject 0x630b
001d:err:plugplay:process_IOService_Device Unable to create plug in interface for USB deviceobject 0x630f
001d:err:plugplay:process_IOService_Device Unable to create plug in interface for USB deviceobject 0x6313
001d:err:plugplay:process_IOService_Device Unable to create plug in interface for USB deviceobject 0x6317
001d:err:plugplay:process_IOService_Device Unable to create plug in interface for USB deviceobject 0x631b
001d:err:plugplay:process_IOService_Device Unable to create plug in interface for USB deviceobject 0x631f
001d:err:plugplay:process_IOService_Device object 0x8a1f
001d:err:plugplay:process_IOService_Device object 0x8703
001f:fixme🧵create_user_shared_data_thread Creating user shared data update thread.
0009:err:mscoree:CLRRuntimeInfo_GetRuntimeHost Wine Mono is not installed

**Comment by Gcenx** [comment]
While this is the correct place for issues related to wine-crossover-* packages the issue is you need to install a native versions of .Net using Winetricks as CrossOver-20 and lower don’t make use of wine-mono.

**Comment by Gcenx** [comment]
I’d recommend using wine-crossover over wine-crossover-19.0.2 package this will avoid `4GB limit for 32-bit-on-64-bit process` as macOS Big Sur had memory mapping differences when compared to macOS Catalina.

**Comment by AnupPlays** [comment]
Im not very experienced with this. When you say install a native version of .Net how would I go about that?

**Comment by Gcenx** [comment]
Tou would do this the Winehq recommended way by using winetricks

Here’s the terminal command to install winetricks then install .Net 4.8
```
brew install winetricks
winetricks -q dotnet48
```
