### ISSUE TITLE
Merge of resolved Bug#40649

### ISSUE THREAD

**Issue by bikeridercz** [Gcenx/homebrew-wine#21]
Dear Friend, let me ask if it is possible to somehow merge the resolution of the [BUG#40649](https://bugs.winehq.org/show_bug.cgi?id=40649) into next update of your Wine-crossover build. Thanks.

**Comment by Gcenx** [comment]
This was added in wine-5.6 and doesn’t apply cleanly onto CX20 sources so would require additional patch(es) to get this to apply, but that doesn’t mean it would work within `wine32on64`

I also don’t know when/if I’ll be doing any rebuilds of CX20.0.2 for this tap.

**Comment by Gcenx** [comment]
I won’t be backporting the fix into the `wine-crossover` packages, this will already be included in the later CX21 based packages.
