### ISSUE TITLE
Avast quarantine

### ISSUE THREAD

**Issue by ToniCHiQuit** [Gcenx/homebrew-wine#23]
Hi, while installing via Hombrew, my antivirus(Avast) detected as threats "win32:suspbehav-B [heur]" in a multitude of files. What is this?

**Comment by Gcenx** [comment]
You need to contact your AntiVirus/AntiMalware vender to connect these false positives.\
This started once wine moved to using *Mingw-gcc* to compile PE binaries.

__See the following examples;__
- [CrossOver 19 and anti virus programs](https://www.codeweavers.com/support/forums/general/?t=27;msg=222870)
- [Windows Defender detects Occamy.c trojan in steam proton 5.0 folder](https://github.com/ValveSoftware/Proton/issues/3593)

Copy/Paste from my WineskinServer project.

**Comment by ToniCHiQuit** [comment]
Thank you for your quick response!  I was not reassured because by searching on the internet I find a lot of issues on viruses

**Comment by Gcenx** [comment]
As explained those are false positives it’s so common that CodeWeavers even added a guide on how to ignore there files with multiple anti virus venders to incorrectly flag wine’s files as virus see https://www.codeweavers.com/support/wiki/mac/mactutorial/bitdefender

If you still don’t trust these files are safe you can scan the flagged quarantines files using TotalVirus online scanner.

Alternatively you can build wine from source on your own stream, a minim of clang-3.8 or later (Xcode7 ish?), bison 3.0, mingw-w64 and XQuartz are required for a basic wine compilation.

**Comment by ToniCHiQuit** [comment]
Okay, thank you very much, I think I just needed to be reassured a little^^
