### ISSUE TITLE
Cannot run flopzilla

### ISSUE THREAD

**Issue by axelbojrup** [Gcenx/homebrew-wine#31]
https://www.flopzilla.com/download.html

Installing pro version on Mac m1 from above hangs with the following messages:

`wine start Downloads/FlopzillaPro205.msi
017c:fixme:exec:SHELL_execute flags ignored: 0x00000100
➜  ~ 018c:fixme:file:NtLockFile I/O completion on lock not implemented yet
018c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
018c:fixme:wincodecs:jpeg_decoder_get_metadata_blocks stub
018c:fixme:wincodecs:jpeg_decoder_get_metadata_blocks stub
018c:fixme:msi:event_spawn_wait_dialog doing nothing
018c:fixme:wincodecs:jpeg_decoder_get_metadata_blocks stub
018c:fixme:wincodecs:jpeg_decoder_get_metadata_blocks stub
018c:fixme:wincodecs:jpeg_decoder_get_metadata_blocks stub
018c:fixme:wincodecs:jpeg_decoder_get_metadata_blocks stub
018c:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
018c:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
018c:fixme:wincodecs:jpeg_decoder_get_metadata_blocks stub`

This is after I have clicked through the installer and pushed the 'finish' button. Given there is a directory for the installation it seems the installation was successful. When I run:

`wine .wine/drive_c/Program\ Files\ \(x86\)/FlopzillaPro/FlopzillaPro/FlopzillaPro.exe`

there is no response and no output. Please let me know how I can provide further information.

**Comment by Gcenx** [comment]
You've used an invalid PATH to the installed executable as I could launch it but get the following error message from it
![Screen Shot 2021-12-18 at 3 35 09 PM](https://user-images.githubusercontent.com/38226388/146654853-91330906-3db8-4bb5-a0ab-92c336303f73.png)
I've seen this come up constantly on CodeWeavers forms without an fix.
