### ISSUE TITLE
Compiling with Vulkan, MoltenVK support?

### ISSUE THREAD

**Issue by autumnjolitz** [Gcenx/homebrew-wine#32]
When I run the `vulkan_test.exe` (from https://github.com/skeeto/vulkan-test) with wine-6.0 (`crossover`), I get:

```
(cpython37) InvincibleReason:~$ wine Downloads/vulkan_test.exe
0960:err:vulkan:get_vulkan_driver Wine was built without Vulkan support.
0960:err:vulkan:wine_vk_init Failed to load Wine graphics driver supporting Vulkan.
(cpython37) InvincibleReason:~$
```

How do you compile this from sources? I would love to see if it's possible to run games like Dishonored 2, GTA 5, etc, using MoltenVK.

**Comment by Gcenx** [comment]
This was purposely compiled without Vulkan support.

To compile from source see https://github.com/GabLeRoux/macos-crossover-wine-cloud-builder/pull/29

If you just want something prebuilt use Wineskin with WS11WineCX64Bit21.1.0 and install the provided dxvk_macos.verb or use PortingKit for a supported title. GTA5 isn't a provided Port _yet_ via PortingKit but I know Paul is interested in getting that up and running at some point.

**Comment by autumnjolitz** [comment]
Interesting. I did try the Wineskin you suggested and followed the WineskinServer/Home page carefully.

Despite installing the dependencies (vcredist, etc) in the Tips and Tricks, then proceeding onto dxvk_macos.verb, then Steam and using `-no-browser +open steam://open/minigameslist`, it routinely faults upon exiting with the log message:

```
021c:err:module:find_forwarded_export module not found for forward 'winevulkan.wine_vkGetInstanceProcAddr' used by L"C:\\windows\\system32\\vulkan-1.dll"
wine: Unhandled page fault on execute access to 00000000 at address 00000000 (thread 021c), starting debugger...
021c:err:seh:start_debugger Couldn't start debugger L"winedbg --auto 536 56" (2)
Read the Wine Developers Guide on how to set up winedbg or another debugger
0170:fixme:file:ReplaceFileW Ignoring flags 2
```

Launching anything that is dx11+ enabled blows up. Black Mesa did so with `07fc:err:vulkan:get_vulkan_driver Wine was built without Vulkan support.` in it's log. Space Marine just didn't even give any info. 

The dream of an operational Vulkan + DXVK running on a Mac seems to fleeting. I'm giving up for now. Thanks for the advice. I've never gotten so close and yet it still bedevils me.

**Comment by Gcenx** [comment]
Just like CrossOver-20+ Wineskin only supports 64Bit DirectX-10/11 as Vulkan on macOS uses the Metal API.\
Heres me demonstrating the [Witcher3](https://youtu.be/ZPedXEMQNZU) on my M1 Mac Mini (community members donated to make the purchase)

For a functional Steam client see [WineskinServer/wiki#steam](https://github.com/Gcenx/WineskinServer/wiki#steam)

Since pushing WineCX21.1.0 Engines Paul had been busy bumping multiple ports on PortingKit including some titles that require DXVK like ANNO2070, along with some none DXVK related things like some games from Origin.
