### ISSUE TITLE
Broken cask ln new version

### ISSUE THREAD

**Issue by egorgam** [Gcenx/homebrew-wine#36]
Last update is broke all homebrew commands (like upgrade or doctor)

Error in terminal:

```
Cask 'unofficial-wineskin' is unreadable: /usr/local/Homebrew/Library/Taps/gcenx/homebrew-wine/Casks/unofficial-wineskin.rb:1: syntax error, unexpected <<
<<<<<<< HEAD
^~
/usr/local/Homebrew/Library/Taps/gcenx/homebrew-wine/Casks/unofficial-wineskin.rb:5: syntax error, unexpected ===, expecting end
=======
^~~
/usr/local/Homebrew/Library/Taps/gcenx/homebrew-wine/Casks/unofficial-wineskin.rb:14: syntax error, unexpected >>, expecting end
>>>>>>> cd3fe3f (cleanup casks)
^~
/usr/local/Homebrew/Library/Taps/gcenx/homebrew-wine/Casks/unofficial-wineskin.rb:28: syntax error, unexpected end, expecting end-of-input
```

**Comment by Gcenx** [comment]
Please untap & retap should resolve the issue. This happened while working on `mingw-w64@9` https://github.com/Gcenx/homebrew-wine/commit/ac003935707f8a43eb15a29119dc8aed249cc21d

**Comment by hworth** [comment]
> Please untap & retap should resolve the issue. This happened while working on `mingw-w64@9` [ac00393](https://github.com/Gcenx/homebrew-wine/commit/ac003935707f8a43eb15a29119dc8aed249cc21d)

Sorry, can you elaborate on what commands exactly should be run? I attempted to untap gcenx/wine but it still through the same error message as provided by @egorgam above.

**Comment by Gcenx** [comment]
Here's my running tap and untap
```
Deans-MBP:~ gcenx$ brew untap gcenx/wine
Untapping gcenx/wine...
Untapped 6 casks (23 files, 111.3KB).
Deans-MBP:~ gcenx$ brew tap gcenx/wine
==> Tapping gcenx/wine
Cloning into '/Users/gcenx/homebrew/Library/Taps/gcenx/homebrew-wine'...
remote: Enumerating objects: 504, done.
remote: Counting objects: 100% (504/504), done.
remote: Compressing objects: 100% (361/361), done.
remote: Total 504 (delta 343), reused 253 (delta 133), pack-reused 0
Receiving objects: 100% (504/504), 75.39 KiB | 3.77 MiB/s, done.
Resolving deltas: 100% (343/343), done.
Tapped 6 casks (23 files, 111.3KB).
Deans-MBP:~ gcenx$ 
```

And here's the output I'm getting from `brew doctor`
```
Deans-MBP:~ gcenx$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 11.3.1.


Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /usr/local/bin/python3.9-config
  /usr/local/bin/python3-config

Warning: You are using macOS 10.14.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.


Warning: Your Homebrew's prefix is not /usr/local.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/usr/local).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
unsupported configuration.
```

I don't have `brew` installed into `/usr/local` instead installed into but `~/$HOME` as I don't like that brew takes over `/usr/local/`

**Comment by auscompgeek** [comment]
```console
% brew untap gcenx/wine
Error: Cask 'wine-crossover' is unreadable: /usr/local/Homebrew/Library/Taps/gcenx/homebrew-wine/Casks/wine-crossover.rb:6: syntax error, unexpected <<, expecting end
<<<<<<< HEAD
^~
/usr/local/Homebrew/Library/Taps/gcenx/homebrew-wine/Casks/wine-crossover.rb:19: syntax error, unexpected ||, expecting end-of-input
||||||| parent of cd3fe3f02cf8 ...
^~
% brew doctor
Error: Cask 'wine-crossover' is unreadable: /usr/local/Homebrew/Library/Taps/gcenx/homebrew-wine/Casks/wine-crossover.rb:6: syntax error, unexpected <<, expecting end
<<<<<<< HEAD
^~
/usr/local/Homebrew/Library/Taps/gcenx/homebrew-wine/Casks/wine-crossover.rb:19: syntax error, unexpected ||, expecting end-of-input
||||||| parent of cd3fe3f02cf8 ...
^~
```
I think I'll have to manually delete this tap.

**Comment by Gcenx** [comment]
It does seem that may be required in your cases, hopefully now that the taps casks pass brew testbot there shouldn’t be a need to rebase the master branch in the future (I hope)

**Comment by egorgam** [comment]
So, you can remove manually git conflict code in /usr/local/Homebrew/Library/Taps/gcenx/homebrew-wine/Casks/unofficial-wineskin.rb, and all will work. Hope author will repair it in repo soon

**Comment by seonar22** [comment]
> ```
> % brew untap gcenx/wine
> Error: Cask 'wine-crossover' is unreadable: /usr/local/Homebrew/Library/Taps/gcenx/homebrew-wine/Casks/wine-crossover.rb:6: syntax error, unexpected <<, expecting end
> <<<<<<< HEAD
> ^~
> /usr/local/Homebrew/Library/Taps/gcenx/homebrew-wine/Casks/wine-crossover.rb:19: syntax error, unexpected ||, expecting end-of-input
> ||||||| parent of cd3fe3f02cf8 ...
> ^~
> % brew doctor
> Error: Cask 'wine-crossover' is unreadable: /usr/local/Homebrew/Library/Taps/gcenx/homebrew-wine/Casks/wine-crossover.rb:6: syntax error, unexpected <<, expecting end
> <<<<<<< HEAD
> ^~
> /usr/local/Homebrew/Library/Taps/gcenx/homebrew-wine/Casks/wine-crossover.rb:19: syntax error, unexpected ||, expecting end-of-input
> ||||||| parent of cd3fe3f02cf8 ...
> ^~
> ```
> 

> I think I'll have to manually delete this tap.

How do I manually delete the tap?

**Comment by itchyny** [comment]
I fixed this issue by `brew update-reset`. If this command doesn't work, try `cd "$(brew --prefix)/Library/Taps/gcenx/homebrew-wine" && git reset --hard && git rebase --abort && git pull --rebase`.

**Comment by hworth** [comment]
> I fixed this issue by `brew update-reset`. If this command doesn't work, try `cd "$(brew --prefix)/Library/Taps/gcenx/homebrew-wine" && git reset --hard && git rebase --abort && git pull --rebase`.

`brew update-reset` also worked like a charm to fix my error message 👍🏻

**Comment by Gcenx** [comment]
Thank you to everyone who provided instructions on fixing my screwup, I believe it’s been left open long enjoy the and should now be safe to close
