### ISSUE TITLE
wine-devel target URL invalid

### ISSUE THREAD

**Issue by bl4ckcontact** [Gcenx/homebrew-wine#4]
Installing wine 5.19 of wine-devel results in a 404 error. I've been able to verify the cause of this issue is due to the change in archive packaging from .tar.gz to .tar.7z on your releases page. 

Thank you for keeping this maintained!

**Comment by Gcenx** [comment]
Seems my attempt to automate this process more caused this change, the Winehq packages should have remained the same only my Wineskin Engines should be using .tar.7z

I can ether repackage or alter the cask to use 7z and add
```
depends_on formula: “p7zip”
 ``

Well that’s what the cask documentation says.

**Comment by Gcenx** [comment]
@bl4ckcontact this should now be resolved, thanks for opening the issue.
