### ISSUE TITLE
Clipboard copy/paste from macOS stops working after I set my Z: target dir? (wine-crossover)

### ISSUE THREAD

**Issue by fiendish** [Gcenx/homebrew-wine#41]
If I change the target folder for the `Z:` drive to be something other than `/` in winecfg, then I stop being able to copy/paste between macOS and Wine.

<img width="403" alt="Screen Shot 2022-03-25 at 11 18 48 AM" src="https://user-images.githubusercontent.com/201996/160149346-37419543-85f4-4d87-b04d-02e09e199e88.png">

I had set it to my user home directory because otherwise my terminal fills up with
> wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.

(The error message doesn't appear to cause any actual issues. It's just spammy.)

I just set it back to `/` and my copy/paste started working again. Any ideas?

**Comment by fiendish** [comment]
Followup, it's possible that changing Z: is a red-herring. My copy/paste stopped working again until I quit and restarted the Wine app. This is weird and unfortunate. It was working perfectly basically forever. Though I did just recently reinstall the package. Did something change in wine-crossover?

**Comment by Gcenx** [comment]
The last time `wine-crossover` was modified was https://github.com/Gcenx/homebrew-wine/commit/bbbe0129157cc22bbad8a7f70ba9ee57323f525d so December 5th 2021, that was simply a rebuild that removed 32Bit support forcing macOS Catalina and later so I doubt the copy/paste issue is related.

The annoying spam about getting the drivers name/serial number is from upstream wine at the time, honestly can’t remember if this has changed upstream or not maybe I’ll check once I’m dealing with the wine-7.5 packages.
