### ISSUE TITLE
Crossover 21.2

### ISSUE THREAD

**Issue by lonewolf1870** [Gcenx/homebrew-wine#42]
Hi,
thanks for effort you do, really great!
Any hope you could update the Crossover bottle to 21.2?

**Comment by Gcenx** [comment]
The changes between CX21 releases is very minimal and would have little to no affect with how this was configured.

Due to how this works it had taken rather a lot of modifications to function so closely to upstream so without some huge change I don’t see myself updating this.

**Comment by lonewolf1870** [comment]
Well, one major difference (at least for me) is the update to OpenCL 1.2
As it currently stands, I have to instances of Wine: your Crossover 21 for 32bit apps, and Wine 7 for 64bit & OpenCL apps.
Not a big deal for me indeed, and I have no idea how much effort it requires for you to update to Crossover 21.2
So, thanks anyway

**Comment by Gcenx** [comment]
Crossover hasn’t modified OpenCL in CX21.2 you can see this via my mirror https://github.com/Gcenx/winecx/tree/crossover-wine/dlls/opencl this component was last updated 9 months ago meaning the original CX21 release.

The OpenCL improvements won’t land until CX22 that’s based on wine-7.x
