### ISSUE TITLE
brew install wine

### ISSUE THREAD

**Issue by OjusG** [Gcenx/homebrew-wine#47]
PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /private/tmp/cmslut-3cea39.c
clang: note: diagnostic msg: /private/tmp/cmslut-3cea39.sh
clang: note: diagnostic msg: Crash backtrace is located in
clang: note: diagnostic msg: /private/tmp/wine-20220524-22962-11t7e8x/wine-7.0/.brew_home/Library/Logs/DiagnosticReports/clang_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
clang: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
clang: note: diagnostic msg: 

********************
make: *** [libs/lcms2/src/cmslut.o] Error 254
make: *** Waiting for unfinished jobs....

when trying: 

make install CC=/usr/bin/clang CXX=/usr/bin/clang++ LD=/usr/bin/ld

I have no "private" directory so not sure where to fetch cache from.

**Comment by Gcenx** [comment]
If your force building from source then you could add `--keep-tmp` and you'd find the files in `/tmp`

Not sure why you'd need to build this from source as I have provided a bottle for Big Sur (built using github actions), this would also be usable on Monterey. Alternatively you could use the wine-stable cask

**Comment by OjusG** [comment]
I ended up downloading wine-stable cask but when I try the command wineboot I get another error:

/opt/homebrew/bin/wineboot: line 46: /opt/homebrew/bin/wine: Bad CPU type in executable
/opt/homebrew/bin/wineboot: line 46: /opt/homebrew/bin/wine: Undefined error: 0

**Comment by Gcenx** [comment]
The wrapper scripts by default directly call `wine` however as your running macOS Catalina or later you’ll need to instead bypass the wine provided wrapper scripts and install do `wine64 wineboot`, `wine64 winecfg`, `wine64 explorer` or anything similar 

Pleaser remember at this time upstream wine only support 64Bit windows binaries on macOS Catalina and later, once this changes so will these packages.

However if must run 32Bit windows binaries you’ll instead want to install the custom package `wine-crossover`, this will allow running 32Bit & 64Bit windows binaries however I’d disabled Vulkan support.

**Comment by Gcenx** [comment]
The download script won’t improve it’s the current limitation of CrossOver 32on64 as that script uses the`wine-crossover` cask I’m currently providing here.
