### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by cereyanli** [Gcenx/homebrew-wine#5]
How can I uninstall it ?

**Comment by Gcenx** [comment]
What are you wanting to uninstall?

**Comment by cereyanli** [comment]
Hi I installed crossover wine from homebrew using your script. How can I uninstall it properly?

**Comment by Gcenx** [comment]
You’d ununstalll the cask as you normally would

`brew cask uninstall wine-crossover`
This won’t remove ~/.wine

To remove the tap;
`brew I tap gcenx/wine`
