### ISSUE TITLE
Can not move window to another screen

### ISSUE THREAD

**Issue by bikeridercz** [Gcenx/homebrew-wine#50]
Dear friend, I'm using **winecx** for years successfully, many thanks for that ! Now I need to move a **Wine** window running wine application to another desktop on external monitor, but unfortunately **Wine's** window does not contain a Mac's standard **red/orange/green dots** nor standard menu option like **Window** ... I'm running a **Wine** application from inside of **.app** package with **Contents/MacOS etc** folder structure ... So I'm wondering if there is somewhere a config file controlling of appearance of window header ... 

+ update: when running an application from command window with "wine ~/.wine/drive_c/.../X.exe" command, then the "Window" option appears OK on Windows's top bar. 

+ update: when starting application from .app bundle with "wine **-start**" option a new instance of program is invoking but second icon appears on the dock, **Window menu** appears successfully with option move to Dell monitor ...

+ update: I've created a question to this topic too on WineHQ forum: https://forum.winehq.org/viewtopic.php?f=9&t=36573#p137288

Can you help ? Thanks.

**Comment by Gcenx** [comment]
Don’t run applications using `Contents/MacOS/wine` binary that’s just to assist with “open with” and direct launches of the app bundle.

You should instead be directly calling `wine` command that’s added to `PATH` when installed via brew.

**Comment by bikeridercz** [comment]
Dear Gcenx, I do not install Wine via BREW. I use "Wine Crossover.app" located in /Application folder instead. So my usual way how to run application is for example ...
`/Applications/Wine\ Crossover.app/Contents/Resources/wine/bin/wine ~/.wine/drive_c/Program\ Files/Sparx\ Systems/EA/EA.exe`

in that particular example, everything works OK, EA is opened with "Window" option o top bar with possibility to move EA to external display.

However, where I run the same but from the bundle EA.app, ie. with the same command inside the EA.app/Contents/MacOS/EA, then EA is opened however without "Window" option on top bar ...

So I thought that there is some option inside of EA.app/Contents/Info.plist that enables a Windows menu option, but I was wrong, there is nothing like that ...

This is what I need to resolve ... Thanks for help.

**Comment by Gcenx** [comment]
You’ve not providing much context here so I’ll need to make some assumptions.

What you've said above sounds like your attempting to make a self contained “app” using a bash script that launching the desired EA.exe but your wondering _why_ there’s none of the usual functions in the menu bar?

**Comment by bikeridercz** [comment]
Yes.

My EA.app is not selfcontained application bacause it does not containt enything else than the bash script. The main reason I made it is that this EA.app can be easily placed in the dock to run EA.app (directly from the dock) by one mouse click.

Thanks.
