### ISSUE TITLE
failed to read display config

### ISSUE THREAD

**Issue by ellipticaldoor** [Gcenx/homebrew-wine#51]
I installed wine on an m1 with this command
```sh
brew install wine-stable-legacy
```
and then I tried to install steam
```
WINEARCH=win64 WINEPREFIX=~/.wine64 wine64 ~/Downloads/SteamSetup.exe
```

but I get the following error
```
0050:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
0048:err:system:update_display_cache failed to read display config
```

is there no support for m1 maybe?

**Comment by Gcenx** [comment]
`wine-stable-legacy` was provided to workaround a bug that affects macOS High Sierra and below. The standard `wine-stable` cask would be preferred for macOS Mojave and later.

Upstream wine is still not capable of running 32Bit Windows binaries on 64Bit only versions of macOS, for this you should use `wine-crossover`

**Comment by ellipticaldoor** [comment]
oh thank you! I see, right now I managed to run 32bits games on wine-crossover but 64bits are not working

**Comment by ellipticaldoor** [comment]
when trying to use wine-stable I get this error
```
WINEARCH=win64 WINEPREFIX=~/.wine64 WINELOADER=/opt/homebrew/bin/wine64 wine64 ~/Downloads/SteamSetup.exe
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: Internal error.
```

**Comment by Gcenx** [comment]
As explained above only `wine-crossover` will be able to run 32Bit Windows binaries at this time.
