### ISSUE TITLE
Required custom formulas

### ISSUE THREAD

**Issue by Gcenx** [Gcenx/homebrew-wine#52]
Need to make the following custom formulas
- ~~epoll-shim~~
- [x] tapi (ld64 requirement) #57 
- [ ] ld64 (modify version restriction for `-no_new_main`)
- ~~libinotify~~

**Comment by Gcenx** [comment]
It seems that `epoll-shim` won’t be too useful for wine at least.

**Comment by Gcenx** [comment]
Seems that `libinotify` would also be useless for wine on macOS.

**Comment by Torrekie** [comment]
epoll-shim already supported Darwin as of its latest commit

**Comment by Gcenx** [comment]
> epoll-shim already supported Darwin as of its latest commit

It’s not that it doesn’t support Darwin it’s that it’s not helpful for wine-staging, it does make then messages go away about esync support on the platform.

However after esync is enabled wine ends up crashing, so it’s simpler to simply skip the patchset.

**Comment by Gcenx** [comment]
@Torrekie doing this allows `-no_new_main` to work without setting `-mmacosx-version-min=10.7`?

And yes using `cctools-port` is preferable to Apples stock sources.

**Comment by Torrekie** [comment]
the latest ld64 has completely striped out the functionality of those two options, I'm not sure if that was version related.
Another problem is, to enable LTO feature, we have to use headers from LLVM but Xcode CLT doesn't provided it at all, that means for a custom ld64 to work, we have to compile a LLVM toolchain or find corresponding `llvm-c/lto.h` for currently provided LLVM in CLT

**Comment by Gcenx** [comment]
The headers wouldn’t be too difficult to map out from Apples llvm fork, though I’m not sure it would be worth the effort might be simpler to just skip LTO

**Comment by Gcenx** [comment]
A copy/paste from an unmerged PR from osxcross

```
# Apple LLVM project download URLs look like:
# https://github.com/apple/llvm-project/archive/refs/heads/apple/stable/20200108.zip
# where the branch-to-major-version lookup is the below:
# apple/stable/20210107 = 12
# apple/stable/20200714 = 11
# apple/stable/20200108 = 10
# apple/stable/20190619 = 9
# apple/stable/20190104 = 8
# apple/stable/20180801 = 7
# apple/stable/20180103 = 6
# apple/stable/20170719 = 5
# apple/stable/20170116 = 4
```

So technically ld64 could be built against Xcode command line tools and make use of its shipped LTO library with a little fines.

**Comment by Torrekie** [comment]
then skipping LTO is okay

**Comment by Gcenx** [comment]
Been working on a `wine-crossover` formula but due to brew relocation functions it’s resulting in a broken 32on64 slice.

As Macports _doesn’t_ do any relocation automatically I’d managed to get `wine-crossover` working completely within it’s environment.

With CX22 touching wines .so binaries breaks 32on64 bar like 3 files.
