### ISSUE TITLE
Homebrew formulae for wine-crossover

### ISSUE THREAD

**Issue by Torrekie** [Gcenx/homebrew-wine#54]
is there any compilation process for currently provided wine-crossover build?

**Comment by Gcenx** [comment]
Your question and title don’t match up so just want to verify what your really asking here.

**Comment by Torrekie** [comment]
sorry for my unmatched title and content, but I wonder if there is any homebrew formulae or other compilation instructions so I could build it on my device

**Comment by Gcenx** [comment]
> sorry for my unmatched title and content.

It's fine just wanted to be sure I'm answering the question.

> I wonder if there is any homebrew formulae

I was working on a `wine-crossover` formula but ran into problems on the `-mwine32` slice and didn't really get change to dig too deeply into it.

> or other compilation instructions so I could build it on my device

If you wanted to simply compile from source you could use https://github.com/GabLeRoux/macos-crossover-wine-cloud-builder, the problem with that method (just like a brew formula) is once brew makes a breaking change to any of the required dependencies you'd need to re-compile from source again. A cask avoids problems with every changing dependencies.

**Comment by Gcenx** [comment]
I’ve updated the cloud builder to now produce a functional CX22.0.0 based build.

Annoyingly the formula still won’t cooperate it will build but the WoW64 slice simply doesn’t work but build using the exact same steps works outside of the brew formula, so assuming there something else brew does that breaks it what _fun_
