### ISSUE TITLE
Wrong download URL in gcenx-wine-devel

### ISSUE THREAD

**Issue by giovariot** [Gcenx/homebrew-wine#7]
Last [commit](https://github.com/Gcenx/homebrew-wine/commit/0644fa3d349b7052c9160fe79f1c72c71f658dd5) has moved the release download file from p7zip to xz.

Unfortunately the download url is still pointing to a 7z file that's been replaced with an xz one

```ruby
cask 'gcenx-wine-devel' do
  version '5.22'
  sha256 :no_check
  
  url "https://github.com/Gcenx/macOS_Wine_builds/releases/download/#{version}/wine-devel-#{version}-osx64.tar.7z"
  
  name 'Wine-devel'
  homepage 'https://github.com/Gcenx/macOS_Wine_builds'
  
  depends_on formula: 'xz'
```

While it should probably be:
```ruby
cask 'gcenx-wine-devel' do
  version '5.22'
  sha256 :no_check
  
  url "https://github.com/Gcenx/macOS_Wine_builds/releases/download/#{version}/wine-devel-#{version}-osx64.tar.xz"
  
  name 'Wine-devel'
  homepage 'https://github.com/Gcenx/macOS_Wine_builds'
  
  depends_on formula: 'xz'
```

Thanks a lot for the great work.

**Comment by Gcenx** [comment]
I changed the `depends_on` but forgotten to fix the url sigh...

Thanks for letting me know I’ll correct this shortly (you can tell I don’t really use homebrew)

**Comment by giovariot** [comment]
Thanks a lot!

**Comment by Gcenx** [comment]
Fix with commit https://github.com/Gcenx/homebrew-wine/commit/61533f3b57e8c309f6f99bf8bed9561929b4f6e4
