### ISSUE TITLE
no longer available for m1?

### ISSUE THREAD

**Issue by mjonsson1986** [Gcenx/homebrew-wine#71]
i have the m1? wine 7.7 installed. but when i do brew install wine-crossover it says it require a x86_64 processor.  i assumed it should say that wine-crossover allready installed

**Comment by Gcenx** [comment]
You need to run the following command as per the README.md
```
brew install --cask --no-quarantine gcenx/wine/wine-crossover
```

<br>

_Not_ doing this will default to the newly added formula `wine-crossover`\
The formula is built from crossover-sources-21.2.0, It would have also been 22.0.1 but brew relocation breaks it.
