### ISSUE TITLE
Double-clicking on .exe file does not properly launch (wine-crossover)

### ISSUE THREAD

**Issue by Sifl46** [Gcenx/homebrew-wine#73]
While running a exe file through CLI works as expected, running a exe via double clicking instead opens up the terminal with the "Welcome to wine-7.7 (CrossOverFOSS 22.0.1)." message as if Wine Crossover.app was directly launched.

Latest wine-crossover Cask
M1 Mac Mini
Ventura 13.0.1

**Comment by OiCkilL** [comment]
I have the same problem too.

**Comment by Gcenx** [comment]
Oh your referring to “Open With” I’ll take a look at it when I’ve got some free time.

**Comment by Gcenx** [comment]
This has now been resolved.
