### ISSUE TITLE
32bit prefixes?

### ISSUE THREAD

**Issue by mjonsson1986** [Gcenx/homebrew-wine#75]
seems this wine-crossover on m1 macs hates 32bit prefixes. some old stuff require 32bits prefixes..

**Comment by Gcenx** [comment]
Unfortunately CodeWeavers didn’t leave and useful notes on how to generate a 32Bit wineprefix with a crossover-sources-22.0.x source build.

This was easily possible with a crossover-sources-21.2.0 and prior builds that used wine32on64, with the transition to upstreams WoW64 this stoped working.

**Comment by mjonsson1986** [comment]
yes it had worked before

**Comment by mjonsson1986** [comment]
possible to downgrade to the old working wine-crossover on a m1 mac?

**Comment by mjonsson1986** [comment]
i allways get to 7x serie. i want the 6x

**Comment by Gcenx** [comment]
> i allways get to 7x serie. i want the 6x

I’m not sure what your doing wrong as you can check the formula yourself and see it’s CX21.2.0 aka wine-6.0 https://github.com/Gcenx/homebrew-wine/blob/master/Formula/wine-crossover.rb

As explained this _must_ me ran from an Intel brew installation aka /usr/local/bin/brew not /opt/homebrew/bin/brew

**Comment by mjonsson1986** [comment]
yes i get an wine64 binary. but not the "wine" command and not the wine-crossover in the app folder

**Comment by Gcenx** [comment]
You could manually create symlinks

wine > wine32on64
wine-preloader > wine32on64-preloader

As I use Macports I’m not familiar with how todo something within brews formula files, I’ll happily accept a PR that does this within the formula.
