### ISSUE TITLE
Build wine-crossover 20.*

### ISSUE THREAD

**Issue by maxgorovenko** [Gcenx/homebrew-wine#8]
I read, you've asked not to create issues here, but I think its exactly local.

There is already crossover-sources-20.0.2.tar.gz. Could you be so kind and build it to this repo? I got an issue with error "cannot open oreans.vxd driver" and it seem to be fixed in 20.*

**Comment by Gcenx** [comment]
I currently don’t plan on providing and updated “wine crossover” package at this time.

I’m aware of the sources being available and updated my [mirror](https://github.com/Gcenx/winecx/tree/crossover-wine) accordingly.

Until I have an M1 system on hand I don’t have any real need to desire to provide an updated package.

**Comment by Gcenx** [comment]
Seems the issue your mentioning is    
[Catlina "oreans.vxd driver" issue](https://www.codeweavers.com/support/forums/general/?t=27;msg=222837), according to the recent bump this issue was not resolved within CrossOver-20.0.x and is lightly related to her ELF to PE transition

**Comment by maxgorovenko** [comment]
We have already build crossover from sources and the problem left.

**Comment by randy-girard** [comment]
@maxgorovenko would you be able to share your build, or configuration how you built it? I am having various issues building it myself. Thanks
