### ISSUE TITLE
Warning: Unexpected method 'revision' called on Cask wine-crossover.

### ISSUE THREAD

**Issue by NethumL** [Gcenx/homebrew-wine#81]
When I run `brew update` (and other commands such as `brew outdated` and `brew autoremove`), I get the following warning:
```
Warning: Unexpected method 'revision' called on Cask wine-crossover.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
```

I ran `brew update-reset && brew update` as instructed in that link, but the warning is still there.

As far as I can tell, it's coming from line 3 in the wine-crossover Cask:
https://github.com/Gcenx/homebrew-wine/blob/0825d1a8591b0b675272b0f64b0802cf65baa2d7/Casks/wine-crossover.rb#L3

I checked other Formulae and Casks, and I found that the syntax `revision 1` is used in other formulae (without quotes). Removing the quotes in the local formula didn't seem to help. Removing the line entirely gets rid of the warning though.

I also found the syntax `revision: "0bfe423"`, but that was when specifying the URL (I think [this](https://docs.brew.sh/Cask-Cookbook#git-urls) is the relevant doc for that syntax)

I found documentation for the 'revision' method in the [Formulae cookbook](https://docs.brew.sh/Formula-Cookbook#formulae-revisions), but not in the Cask cookbook. It looks like it's only valid for Formulae. 

OS: macOS BigSur 11.7.1 (20G918)
Brew version details
```sh
$ brew --version
Homebrew 3.6.13-2-gcb355a2
Homebrew/homebrew-core (git revision b9a1564832f; last commit 2022-11-30)
Homebrew/homebrew-cask (git revision 11c6e1f393; last commit 2022-11-30)
```

**Comment by Gcenx** [comment]
Weird that this change passed the github actions. Then again testbot wasn't really setup to fully test casks.

Once #82 passes I'll merge it and hopefully that resolves this issue.
