### ISSUE TITLE
CLRRuntimeInfo_GetRuntimeHost Wine Mono is not installed

### ISSUE THREAD

**Issue by bloodstrike** [Gcenx/homebrew-wine#9]
Forgive me if I'm not doing something obvious, but I've tried both wine-crossover and unofficial-wineskin (both installed from brew), and both fail to launch the windows .exe with the error 'Wine Mono is not installed' in the log. On the readme it says that wine mono should be included. What am I missing?

**Comment by Gcenx** [comment]
For Wineskin mono is disabled by default as I find it uselessly taking up additional disk space regardless if it’s used or not.

For wine-crossover wine-mono is also disabled within the provided sources, you can use winetricks to install a dotnet verb as needed.
