### ISSUE TITLE
MDAC28 can't be installed on new Prefix

### ISSUE THREAD

**Issue by bikeridercz** [Gcenx/homebrew-wine#94]
Dear friend, this is not a bug, I'm asking for a help.

I'm trying to create brand new Prefix on my new computer. And the very first step is failing. I'm trying to install MDAC28 and the install process fails. I'm sure that there is no problem with installer itself nor with the ODBC control panel that is installed as a result (after installation). This code is successfully running on my already existing few years old Prefix.

Wine version:
`Welcome to wine-7.7 (CrossOverFOSS 22.0.1)`

What I tried:
```
rm -r ~/.wine 
./winetricks mdac28
...
sha256sum mismatch! Rename /Users/radim/.cache/winetricks/mdac28/MDAC_TYP.EXE and try again.
...
```
So downloaded MDAC_TYP.EXE manually from Microsoft site and then tried following ...
```
wine cmd
MDAC_TYP.EXE
...
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
0108:fixme:module:dlopen_32on64_opengl32 loaded "/Applications/Wine Crossover.app/Contents/Resources/wine/lib/wine/x86_32on64-unix/opengl32.dll.so" early @ 0x6a21e000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
0118:fixme:module:dlopen_32on64_opengl32 loaded "/Applications/Wine Crossover.app/Contents/Resources/wine/lib/wine/x86_32on64-unix/opengl32.dll.so" early @ 0x6a151000
...
```

Running _wine explorer_ didn't help too, but I'm getting little different errors ...
```
...
0128:fixme:module:dlopen_32on64_opengl32 loaded "/Applications/Wine Crossover.app/Contents/Resources/wine/lib/wine/x86_32on64-unix/opengl32.dll.so" early @ 0x6a151000
...
0138:fixme:module:dlopen_32on64_opengl32 loaded "/Applications/Wine Crossover.app/Contents/Resources/wine/lib/wine/x86_32on64-unix/opengl32.dll.so" early @ 0x69951000
...
```
<img width="402" alt="image" src="https://user-images.githubusercontent.com/5019226/223945231-4daa5266-8943-466f-a10e-30fb8c0e545f.png">

Seems that those messages points to **dlopen_32on64_opengl32** ...

Any thoughts ?

Many many Thanks.

**Comment by Gcenx** [comment]
You can bypass the checksum mismatch by using `-f` to force the install or `-q` for silent installs.

Installing that manually may require setting a lower windows version within winecfg.

> dlopen_32on64_opengl32

This message just means your running a 32Bit application so it’s preloading the 32on64 copy of opengl32.

**Comment by bikeridercz** [comment]
I still did not solve that weird probled, even setting of windows version to the lowest one (xp) didn’t help. I tried to reproduce the way how MDAC28 is installed by winetricks …
